### ISSUE TITLE
Source attribution

### ISSUE THREAD

**Issue by bjorn3** [antoyo/rustc_codegen_gcc#1]
Hi @antoyo! I just saw this project. I am always exited about the development of alternative codegen backends for rustc. I noticed that you have copied substantial parts of my rustc backend called [rustc_codegen_cranelift](https://github.com/bjorn3/rustc_codegen_cranelift). While I don't have any problems with this, (I licensed it using a permissive dual-license after all) I would greatly appreciate it if you attribute the copied parts to me (and any relevant contributors to rustc_codegen_cranelift).

**Comment by antoyo** [comment]
Sure. I'm not sure exactly how to do that. Can you provide me some pointers? (And sorry for forgetting to do it.)

**Comment by bjorn3** [comment]
The MIT license says:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

The Apache-2.0 license talks about a NOTICE file:

> If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.

An example I could find is https://github.com/apache/httpd/blob/trunk/NOTICE

You could make a NOTICE file and tell which files/directories were copied from rustc_codegen_cranelift, that I am the author, the license and maybe also the exact commit you copied it from. In addition both MIT and Apache-2.0 require you to distribute the license with any works that are (substantial) derivatives. Because I licensed it as MIT OR Apache-2.0 at your option, you can choose to include either license file, or you could include both.

**Comment by antoyo** [comment]
@bjorn3 I opened pull request #2. I couldn't find what your name is so I put your username.
Could you please check that it looks alright?
I'm hoping I didn't forget a file in that list.
Thanks.

**Comment by bjorn3** [comment]
My username is fine. I didn't thoroughly check of you missed a file, but from a quick look at the list it didn't seem like you missed one.

**Comment by antoyo** [comment]
Thanks for the quick review.

And again, sorry for not including that right away.
