### ISSUE TITLE
Do you want the gccjit.rs crates.io package?

### ISSUE THREAD

**Issue by swgillespie** [antoyo/rustc_codegen_gcc#39]
Hey! I see you forked https://github.com/swgillespie/gccjit.rs which I wrote forever ago and haven't maintained since. Do you want ownership over the gccjit.rs crates.io package? I have no intention of pushing it further and I'm too disconnected from the gcc development process to keep up with `libgccjit` API changes and such.

**Comment by antoyo** [comment]
Yes, I'd like that!
I probably won't publish in a while since my patches to libgccjit are not merged yet, but that would be useful when they are.

**Comment by swgillespie** [comment]
Cool! I just sent you an invite to be an owner of the package - feel free to remove me once you're in.

**Comment by antoyo** [comment]
Thanks!
