### ISSUE TITLE
Be able to have GCC dump files

### ISSUE THREAD

**Issue by dkm** [antoyo/rustc_codegen_gcc#44]
It would be nice to have GCC dumps its dump files (-fdump-tree-*, -fdump-rtl-*).

Reading https://rustc-dev-guide.rust-lang.org/backend/debugging.html  , I guess something using some `-C gcc-args=`  ? 
I also don't know how libgccjit works, but if you can simply feed it regular command line options, `-C gcc-args=-fdump-tree-all` would be ok, I guess.

**Comment by antoyo** [comment]
So, it seems you would have to use `-C llvm-args=-fdump-tree-all` instead of `gcc-args`.
Also, that would dump the files in `/tmp/libgccjit-XXXXX`. Would that be alright?

**Comment by davidmalcolm** [comment]
FWIW there's also:
  https://gcc.gnu.org/onlinedocs/jit/topics/contexts.html#c.gcc_jit_context_enable_dump
which lets you capture the dump output as a `const char *`, though I mainly added that for the purpose of a regression test; see the caveat in the docs.

**Comment by dkm** [comment]
> So, it seems you would have to use `-C llvm-args=-fdump-tree-all` instead of `gcc-args`.
> Also, that would dump the files in `/tmp/libgccjit-XXXXX`. Would that be alright?

I guess that could work, I have to reread this part. IIRC, for gcc dump we simply look at `<basefile>.c.*` to list all dumps. Having them along the output file instead of /tmp would be easier I think as several executions won't interfere.

**Comment by antoyo** [comment]
If we use the option that David talked about, we'll be able to specify the output path, but I'm not sure how that would work with `-fdump-tree-all` since there would be multiple files.

**Comment by dkm** [comment]
I guess you would need to have several calls to 
```
   gcc_jit_context_enable_dump (ctxt, "tree-vrp1", &dump_vrp1);
```
one for each pass. Maybe there's a way to iterate over all passes (or generate some code to do that...)

**Comment by davidmalcolm** [comment]
FWIW there's also https://gcc.gnu.org/onlinedocs/jit/topics/contexts.html#c.gcc_jit_context_add_command_line_option but the compilation happens in a tempdir, so you'd need some way of moving the dumps out from there.

**Comment by dkm** [comment]
Oh, that would work. @antoyo if you wire the `-C llvm-args` to this, then I could start playing with it and see if that's enough for compiler explorer's needs! Moving the files out of the temp dir should not be an issue if the temp dir can be found easily (forced or computed from the input)

**Comment by davidmalcolm** [comment]
I don't think that I ever directly expose a way to get at the tempdir via the API, and the tempdir gets deleted as soon as the compilation is done, so it might be tricky to get at the dumps this way.

Would it be simpler to give a way to control the tempdir used for the build from the API?

It might be possible to have a way to iterate through all dumpfiles; IIRC the exact dump names are only available once the compilation has started, which could make things fiddly (gcc's `dump_manager` class).

I'm not sure what the best approach here is.

**Comment by davidmalcolm** [comment]
Another (untested) idea: set the dump file base name to an absolute path; that way the dumps will escape the tempdir and appear where you want.  Not sure if GCC exposes an option for this yet.

**Comment by antoyo** [comment]
As I said in PR #45, it might be tricky to get the actual dumps, not only because they'll be in /tmp, but also because of CGUs: you'll have multiple temp directory to look at.
So feel free to re-open the issue after you explored that a bit and have a better idea of what you'd need.

**Comment by dkm** [comment]
As stated in https://github.com/compiler-explorer/compiler-explorer/issues/2868 I'm trying to have this work :)

After some quick tests, I can see something is not working as expected when using `-dump*` options.
It seems that something is not expecting the paths to changes:

```
$ ./bin/rustc -C panic=abort -Z codegen-backend=librustc_codegen_gcc.so --sysroot ..../build/tost/rustc-cg-gcc-master-20210823/sysroot/ toto.rs -C llvm-args='-dumpbase mybase 
Assembler messages:
Error: can't open /tmp/libgccjit-fZSSpf/fake.s for reading: No such file or directory
libgccjit.so: error: error invoking gcc driver
Assembler messages:
Error: can't open /tmp/libgccjit-8xWUxi/fake.s for reading: No such file or directory
libgccjit.so: error: error invoking gcc driver
Assembler messages:
....
```

But the assembly is correctly in mybase.s:
```
$ cat mybase.s
       .file   "fake.c"
        .intel_syntax noprefix
        .text
.Ltext0:
        .globl  __gccGlobalInittoto_8b7d54db_cgu_5
        .type   __gccGlobalInittoto_8b7d54db_cgu_5, @function
__gccGlobalInittoto_8b7d54db_cgu_5:
...
```
Should I look in your backend's code or in libgccjit? 

Using `-dumpdir` does not seem to do anything:
```
... -C llvm-args='-dumpdir /tmp/mybase/ -fdump-tree-gimple '
```
Still outputs the dump files in temp directories:
```
/tmp/libgccjit-iwjzFt/fake.c.006t.gimple
/tmp/libgccjit-f7DLYs/fake.c.006t.gimple
...
```

I'm happy to dig a bit, but I guess you can already point me in some direction (libgccgit or rustc_cg_gcc)?

**Comment by antoyo** [comment]
I'm not sure if that would help, but you can set the base with using one of [these environment variables](https://github.com/antoyo/gcc/blob/master/libiberty/make-temp-file.c#L118-L120): TMPDIR, TMP, TEMP.
(It seems like rustc also use `TMPDIR`, so you might want to avoid that one.)

This will still create a hierarchy like so:
```
$ tree /tmp/mybase/
/tmp/mybase/
├── libgccjit-3IZu7O
│   └── fake.c.006t.gimple
├── libgccjit-8YQHvc
│   └── fake.c.006t.gimple
```

Otherwise, you might want to read the code of that file to find a way that might suit you.

**Comment by dkm** [comment]
Thanks. I did already tes TMPDIR and it works, but sill have to walk the dirs.I'll check thiis file !

**Comment by antoyo** [comment]
It seems like libgccjit will unconditionally add those directories [here](https://github.com/antoyo/gcc/blob/master/gcc/jit/jit-tempdir.c#L60).

**Comment by dkm** [comment]
Ok thanks, I'll see if I can do something there, thanks. Maybe @dmalcolm has an idea how to handle this better ?

**Comment by dkm** [comment]
Looking at the libgccgit, it seems that I should be able to make it use dump* options for the various files. I'll try to prototype something and see if it's better than simply iterating over $TMP/libgccfit-XXXXX dirs.
