### ISSUE TITLE
rust_codegen_gcc has worse codegen for match with call to functions with identical bodies

### ISSUE THREAD

**Issue by jrmuizel** [antoyo/rustc_codegen_gcc#53]
This code:

```rust
trait A {
    fn k(&self, x: i32) -> i32;
}

pub struct O {
}

pub struct P {
}

impl A for O {
    fn k(&self, x: i32) -> i32 {
        x
    }
}

impl A for P {
    fn k(&self, x: i32) -> i32 {
        x
    }
}

pub enum R {
    P(P),
    O(O),
}
impl R {
    pub fn k(&self, x: i32) -> i32 {
        match self {
            &R::P(ref p) => p.k(x),
            &R::O(ref o) => o.k(x),
        }
    }
}
```

compiles to:
```asm
example::R::k:
        mov     eax, esi
        ret
```
with llvm

but with gcc I get:
```asm
__LT_example__O_u20_as_u20_example__A_GT_::k:
        mov     eax, esi
        ret
__LT_example__P_u20_as_u20_example__A_GT_::k:
        mov     eax, esi
        ret
example::R::k:
        cmp     BYTE PTR [rdi], 0
        je      .L14
        add     rdi, 1
        jmp     __LT_example__O_u20_as_u20_example__A_GT_::k@PLT
.L14:
        add     rdi, 1
        jmp     __LT_example__P_u20_as_u20_example__A_GT_::k@PLT
```

Roughly similar C code doesn't have this problem:
https://gcc.godbolt.org/z/cvr867jd1

**Comment by antoyo** [comment]
This might be because of the current lack of support for inlining. I'll make some tests with my branch that contains some inlining work.

**Comment by bjorn3** [comment]
LLVM also always enables `-fno-semantic-interposition`, while GCC has `-fsemantic-interposition` by default. `-fsemantic-interposition` prevents inlining of exported functions as it has to assume that another shared library interposes the function with different behavior.

**Comment by antoyo** [comment]
I tried to reproduce this issue locally and cannot reproduce it. I'd need to know the exact arguments sent to rustc by godbolt as everything is optimized away when I try.

I changed the example to the following to avoid the dead code to be eliminated:
```rust
trait A {
    fn example(&self, x: i32) -> i32;
}

pub struct O {
}

pub struct P {
}

impl A for O {
    fn example(&self, x: i32) -> i32 {
        x
    }
}

impl A for P {
    fn example(&self, x: i32) -> i32 {
        x
    }
}

pub enum R {
    P(P),
    O(O),
}

impl R {
    pub fn example(&self, x: i32) -> i32 {
        match self {
            &R::P(ref p) => p.example(x),
            &R::O(ref o) => o.example(x),
        }
    }
}

extern "C" {
    pub fn exit(status: i32);
}

fn main() {
    unsafe {
        exit(R::P(P {}).example(std::env::args().collect::<Vec<_>>().len() as i32));
    }
}
```
and the assembly shows that the result of `Vec::len()` is sent directly to `exit()`, completely inlining all the calls:
```asm
00000000000050e0 <_ZN9test_rust4main17hbffb175b880acc4dE>:
    50e0:	55                   	push   rbp
    50e1:	48 81 ec a0 00 00 00 	sub    rsp,0xa0
    50e8:	48 8d 7c 24 20       	lea    rdi,[rsp+0x20]
    50ed:	48 89 e5             	mov    rbp,rsp
    50f0:	e8 d7 6f 26 00       	call   26c0cc <_ZN3std3env4args17h30a41b985a90076bE>
    50f5:	66 0f 6f 44 24 20    	movdqa xmm0,XMMWORD PTR [rsp+0x20]
    50fb:	66 0f 6f 4c 24 30    	movdqa xmm1,XMMWORD PTR [rsp+0x30]
    5101:	48 89 ef             	mov    rdi,rbp
    5104:	48 8d b4 24 80 00 00 	lea    rsi,[rsp+0x80]
    510b:	00 
    510c:	0f 29 84 24 80 00 00 	movaps XMMWORD PTR [rsp+0x80],xmm0
    5113:	00 
    5114:	0f 29 8c 24 90 00 00 	movaps XMMWORD PTR [rsp+0x90],xmm1
    511b:	00 
    511c:	e8 0f fd ff ff       	call   4e30 <_ZN98__LT_alloc__vec__Vec_LT_T_GT__u20_as_u20_alloc__vec__spec_from_iter__SpecFromIter_LT_T_C_I_GT__GT_9from_iter17hdcc6437ad01fa5a6E>
    5121:	8b 7c 24 10          	mov    edi,DWORD PTR [rsp+0x10]
    5125:	e8 d6 f3 ff ff       	call   4500 <exit@plt>
    512a:	48 89 ef             	mov    rdi,rbp
    512d:	e8 ae fc ff ff       	call   4de0 <_ZN70__LT_alloc__vec__Vec_LT_T_C_A_GT__u20_as_u20_core__ops__drop__Drop_GT_4drop17h45face648ead786cE>
    5132:	48 89 ef             	mov    rdi,rbp
    5135:	e8 f6 15 00 00       	call   6730 <_ZN77__LT_alloc__raw_vec__RawVec_LT_T_C_A_GT__u20_as_u20_core__ops__drop__Drop_GT_4drop17h294d402ecbf40451E>
    513a:	48 81 c4 a0 00 00 00 	add    rsp,0xa0
    5141:	5d                   	pop    rbp
    5142:	c3                   	ret    
    5143:	66 66 2e 0f 1f 84 00 	data16 cs nop WORD PTR [rax+rax*1+0x0]
    514a:	00 00 00 00 
    514e:	66 90                	xchg   ax,ax
```

And this is using the master branch of rustc_codegen_gcc.

**Comment by jrmuizel** [comment]
Here's what I was getting on godbolt: https://rust.godbolt.org/z/P8edTcqYG

**Comment by antoyo** [comment]
Yup, I can reproduce it with godbolt, but not locally. I'm trying to understand why…

Possibly godbolt sends different cli arguments to rustc; I'd like to know what are those cli arguments.

**Comment by bjorn3** [comment]
Click on the checkmark next to the custom arguments:

> -C panic=abort -Z codegen-backend=librustc_codegen_gcc.so --sysroot /opt/compiler-explorer/rustc-cg-gcc-master/sysroot -C debuginfo=1 -o /tmp/compiler-explorer-compiler202171-5171-onrkiz.d2xse/output.s --emit asm --crate-type rlib --color=always -O /tmp/compiler-explorer-compiler202171-5171-onrkiz.d2xse/example.rs

**Comment by antoyo** [comment]
Thanks @bjorn3 !

And you were right, using `-fno-semantic-interposition` makes the code exactly the same as LLVM. Do you know if this should always be enabled?

**Comment by bjorn3** [comment]
It probably should always be enabled. For mangled symbols it shouldn't actually be possible to interpose at all, as that breaks the stability guarantee of rustc. For unmangled symbols, there may be cases where it is useful, but given that rustc+cg_llvm doesn't allow it, you shouldn't do it anyway.

**Comment by antoyo** [comment]
If you find any other example where the code is worse, please open a new issue for it.
Thanks!
