### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by tromey** [antoyo/rustc_codegen_gcc#7]
I tried building this today but it failed.
```
   Compiling rustc_codegen_gcc v0.1.0 (/home/tromey/Rust/rustc_codegen_gcc)
error[E0463]: can't find crate for `rustc_ast`
  --> src/lib.rs:18:1
   |
18 | extern crate rustc_ast;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```
I'm not sure if this is something I did wrong or not.

**Comment by antoyo** [comment]
You might need `rustc-dev`:

```
rustup component add rustc-dev
```

**Comment by tromey** [comment]
I must have forgotten `prepare.sh` because I re-ran it, and now it is building.  Sorry about that!  I really thought I had done that.
