### ISSUE TITLE
Reference to HN Article somewhere in this repo...

### ISSUE THREAD

**Issue by stormasm** [antoyo/rustc_codegen_gcc#9]
This is a great reference for other folks to see comments etc...

https://news.ycombinator.com/item?id=27258522

Can you put it somewhere in your repo ?

**Comment by antoyo** [comment]
There's not much info in there. Is there anything specific you would like to see in this repo?

**Comment by stormasm** [comment]
_This is a GCC codegen backend for rustc, so it gets to reuse the existing Rust frontend for free, but benefits from GCC's optimizations and support for more target architectures_ 

is a very nice clean simple explanation of your repo..._

For me, I know its hard when I am so intimately familiar with my own repos to explain what I am doing in a very simple clean, concise way....

**Comment by antoyo** [comment]
A similar description was added in the readme.

Thanks for the suggestion!
